const { contextBridge, ipcRenderer } = require('electron');

const roleArgument = process.argv.find((value) => value.startsWith('--desktop-role='));
const roleFromArgs = roleArgument ? roleArgument.split('=')[1] : 'unknown';

contextBridge.exposeInMainWorld('desktopRuntime', {
  isElectron: true,
  platform: process.platform,
  role: roleFromArgs,
  getRole: () => ipcRenderer.invoke('desktop:get-role'),
  getShellState: () => ipcRenderer.invoke('desktop:get-shell-state'),
  getDesktopSettings: () => ipcRenderer.invoke('desktop:get-settings'),
  setDesktopScale: (scaleKey) => ipcRenderer.invoke('desktop:set-scale', scaleKey),
  getImageUpdateState: () => ipcRenderer.invoke('desktop:get-image-update-state'),
  getDataReleaseUpdateState: () => ipcRenderer.invoke('desktop:get-data-release-update-state'),
  getDataManagementState: () => ipcRenderer.invoke('desktop:get-data-management-state'),
  getUserWorkspaceState: () => ipcRenderer.invoke('desktop:get-user-workspace-state'),
  putUserWorkspaceState: (payload) => ipcRenderer.invoke('desktop:put-user-workspace-state', payload),
  restoreUserWorkspaceSnapshot: (payload) => ipcRenderer.invoke('desktop:restore-user-workspace-snapshot', payload),
  migrateBrowserLegacyArchive: (payload) => ipcRenderer.invoke('desktop:migrate-browser-legacy-archive', payload),
  runDataManagementLegacyMigration: () => ipcRenderer.invoke('desktop:run-data-management-legacy-migration'),
  setImageUpdateConfig: (payload) => ipcRenderer.invoke('desktop:set-image-update-config', payload),
  checkImageUpdate: () => ipcRenderer.invoke('desktop:check-image-update'),
  applyImageUpdate: () => ipcRenderer.invoke('desktop:apply-image-update'),
  checkDataReleaseUpdate: () => ipcRenderer.invoke('desktop:check-data-release-update'),
  applyDataReleaseUpdate: () => ipcRenderer.invoke('desktop:apply-data-release-update'),
  forceClearImageUpdate: () => ipcRenderer.invoke('desktop:force-clear-image-update'),
  pickImageReleaseSourceDir: () => ipcRenderer.invoke('desktop:pick-image-release-source-dir'),
  pickImageReleaseOutputDir: () => ipcRenderer.invoke('desktop:pick-image-release-output-dir'),
  buildImageReleasePackage: (payload) => ipcRenderer.invoke('desktop:build-image-release-package', payload),
  pickDataReleaseSourceDir: () => ipcRenderer.invoke('desktop:pick-data-release-source-dir'),
  pickDataReleaseOutputDir: () => ipcRenderer.invoke('desktop:pick-data-release-output-dir'),
  buildDataReleasePackage: (payload) => ipcRenderer.invoke('desktop:build-data-release-package', payload),
  revealPath: (payload) => ipcRenderer.invoke('desktop:reveal-path', payload),
  quitApp: () => ipcRenderer.invoke('desktop:quit-app'),
  listImageAssets: () => ipcRenderer.invoke('desktop:list-image-assets'),
  importImageAssets: () => ipcRenderer.invoke('desktop:import-image-assets'),
  importImageAssetsToDir: (payload) => ipcRenderer.invoke('desktop:import-image-assets-to-dir', payload),
  renameImageAsset: (payload) => ipcRenderer.invoke('desktop:rename-image-asset', payload),
  renameImageDirectory: (payload) => ipcRenderer.invoke('desktop:rename-image-directory', payload),
  deleteImageAsset: (payload) => ipcRenderer.invoke('desktop:delete-image-asset', payload),
  importImageAssetsFromBrowser: (payload) => ipcRenderer.invoke('desktop:import-image-assets-from-browser', payload),
  createImageDirectory: (payload) => ipcRenderer.invoke('desktop:create-image-directory', payload),
  deleteImageDirectory: (payload) => ipcRenderer.invoke('desktop:delete-image-directory', payload),
  revealInExplorer: (payload) => ipcRenderer.invoke('desktop:reveal-in-explorer', payload),
  readEquipmentLibrary: () => ipcRenderer.invoke('desktop:read-equipment-library'),
  writeEquipmentLibrary: (payload) => ipcRenderer.invoke('desktop:write-equipment-library', payload),
  listLocalDataArchives: () => ipcRenderer.invoke('desktop:list-local-data-archives'),
  saveLocalDataArchive: (payload) => ipcRenderer.invoke('desktop:save-local-data-archive', payload),
  readLocalDataArchive: (payload) => ipcRenderer.invoke('desktop:read-local-data-archive', payload),
  deleteLocalDataArchive: (payload) => ipcRenderer.invoke('desktop:delete-local-data-archive', payload),
  revealLocalDataArchive: (payload) => ipcRenderer.invoke('desktop:reveal-local-data-archive', payload),
  listAiTimelineWorkNodes: () => ipcRenderer.invoke('desktop:list-ai-timeline-worknodes'),
  createAiTimelineWorkNode: (payload) => ipcRenderer.invoke('desktop:create-ai-timeline-worknode', payload),
  readAiTimelineWorkNode: (payload) => ipcRenderer.invoke('desktop:read-ai-timeline-worknode', payload),
  diffAiTimelineWorkNode: (payload) => ipcRenderer.invoke('desktop:diff-ai-timeline-worknode', payload),
  updateAiTimelineWorkNode: (payload) => ipcRenderer.invoke('desktop:update-ai-timeline-worknode', payload),
  commitAiTimelineWorkNode: (payload) => ipcRenderer.invoke('desktop:commit-ai-timeline-worknode', payload),
  markAiTimelineWorkNodeCheckoutApplied: (payload) => ipcRenderer.invoke('desktop:mark-ai-timeline-worknode-checkout-applied', payload),
  markAiTimelineWorkNodeRollbackApplied: (payload) => ipcRenderer.invoke('desktop:mark-ai-timeline-worknode-rollback-applied', payload),
  deleteAiTimelineWorkNode: (payload) => ipcRenderer.invoke('desktop:delete-ai-timeline-worknode', payload),
});
